### ISSUE TITLE
Q&A) Could I use your "eye-blink-counter" for my university project?

### ISSUE THREAD

**Issue by soeun0-8** [zahid214/eye-blink-counter#1]
Hello, zahid214.
I am Soeun0-8, currently attending a university in South Korea. 
First of all, I would like to say that **I love your project**, eye-blink-counter, which is very useful. These days, I am working on an "AI-interview helper" as a university project. "AI-interview helper" helps you prepare for job interviews simply through the website.

I planned to add eye-detection and eye-blinking counter to this project function. But in the process, I experienced a serious issue that py file and HTML were not interlocked. I have had a hard time because of this for 2 weeks, and finally, I discovered your project. When I found "eye-blinking-counter", I thought I could solve my issue by using it. Then, I really solved the problem thanks to you! I was very happy and uploaded this file to the repository. However, after that, I found out that your project is public, but there is no license.

### **Could you please allow me to use, copy, modify, merge, publish, distribute, sublicense your "eye-blink-counter"?** (like MIT License!)
I uploaded the file in CAU-ARTTECH-OSP-01/T07(https://github.com/CAU-ARTTECH-OSP-01/T07.git), so you can freely check which part I modify and distribute. It is an MIT-licensed project, and I will never sell copies of the Software. 
Also, if you allow me, I would like to discuss what I have improved the accuracy of the source code that counts blinking eyes.

Thank you for reading through. I'm sorry about there may be difficult parts to understand because I am not good at English.

**Comment by zahid214** [comment]
yes you can use this.
